// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ContactsSharp {
    
    
    public partial class AboutDialog {
        
        private Gtk.Table table1;
        
        private Gtk.Label aboutLabel;
        
        private Gtk.Label aboutTitleLabel;
        
        private Gtk.Label authorLabel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ContactsSharp.AboutDialog
            this.Name = "ContactsSharp.AboutDialog";
            this.Title = Mono.Unix.Catalog.GetString("About ContactsSharp");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-about", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.HasSeparator = false;
            // Internal child ContactsSharp.AboutDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.aboutLabel = new Gtk.Label();
            this.aboutLabel.Name = "aboutLabel";
            this.aboutLabel.Xalign = 0F;
            this.aboutLabel.LabelProp = Mono.Unix.Catalog.GetString("ContactsSharp is a simple demo app to show capabilities of MonoDevelop, Stetic, GTK# and Mono.");
            this.aboutLabel.Wrap = true;
            this.table1.Add(this.aboutLabel);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.aboutLabel]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.aboutTitleLabel = new Gtk.Label();
            this.aboutTitleLabel.Name = "aboutTitleLabel";
            this.aboutTitleLabel.Xalign = 0F;
            this.aboutTitleLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>About ContactsSharp</b>");
            this.aboutTitleLabel.UseMarkup = true;
            this.table1.Add(this.aboutTitleLabel);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.aboutTitleLabel]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.authorLabel = new Gtk.Label();
            this.authorLabel.Name = "authorLabel";
            this.authorLabel.LabelProp = Mono.Unix.Catalog.GetString("(c) 2009 Denis Fuenzalida");
            this.table1.Add(this.authorLabel);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.authorLabel]));
            w4.TopAttach = ((uint)(3));
            w4.BottomAttach = ((uint)(4));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w5.Position = 0;
            // Internal child ContactsSharp.AboutDialog.ActionArea
            Gtk.HButtonBox w6 = this.ActionArea;
            w6.Name = "dialog1_ActionArea";
            w6.Spacing = 6;
            w6.BorderWidth = ((uint)(5));
            w6.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-close";
            this.AddActionWidget(this.buttonOk, -7);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonOk]));
            w7.Expand = false;
            w7.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 324;
            this.DefaultHeight = 152;
            this.Show();
            this.buttonOk.Clicked += new System.EventHandler(this.OnButtonOkClicked);
        }
    }
}
