Document: privatewiki
Title: Debian privatewiki Manual
Author: <insert document author here>
Abstract: This manual describes what privatewiki is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/privatewiki/privatewiki.sgml.gz

Format: postscript
Files: /usr/share/doc/privatewiki/privatewiki.ps.gz

Format: text
Files: /usr/share/doc/privatewiki/privatewiki.text.gz

Format: HTML
Index: /usr/share/doc/privatewiki/html/index.html
Files: /usr/share/doc/privatewiki/html/*.html

  
