Document: contactssharp
Title: Debian contactssharp Manual
Author: <insert document author here>
Abstract: This manual describes what contactssharp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/contactssharp/contactssharp.sgml.gz

Format: postscript
Files: /usr/share/doc/contactssharp/contactssharp.ps.gz

Format: text
Files: /usr/share/doc/contactssharp/contactssharp.text.gz

Format: HTML
Index: /usr/share/doc/contactssharp/html/index.html
Files: /usr/share/doc/contactssharp/html/*.html
