// Generated by ThinG on 12-ene-2005 22:48:10.

package tests;
import thinlet.Thinlet;
import thinlet.FrameLauncher;

/**
 * A thinlet with the contents of "<code>HTMLRenderer.xml</code>".
 */
public class HTMLRendererHandler extends Thinlet
{

    /**
     * Create a new HTMLRendererHandler instance.
     */
    public HTMLRendererHandler() throws java.io.IOException
    {
        add(parse("HTMLRenderer.xml"));
    }


    /**
     * Show a test frame with the Thinlet contents.
     *
     * @param args  ignored.
     */
    public static void main(String[] args) throws java.io.IOException
    {
        new FrameLauncher("HTMLRendererHandler", new HTMLRendererHandler(), 400, 400);
    }

}
